import {
  LayoutDashboard,
  PanelsTopLeft,
  UsersRound,
  Building2,
  Magnet,
  Columns3,
  MessagesSquare,
  CheckSquare,
  FileText,
  Package,
  Workflow,
  ChartNoAxesCombined,
  Users,
  Settings2,
} from 'lucide-react';
export const navigation = [
  {
    group: 'Visão geral',
    label: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    description: 'Uma visão clara do seu negócio.',
    phase: 12,
  },
  {
    group: 'Comercial',
    label: 'CRM',
    href: '/crm',
    icon: PanelsTopLeft,
    description: 'Relacionamentos, oportunidades e próximos passos.',
    phase: 5,
  },
  {
    group: 'Comercial',
    label: 'Clientes',
    href: '/contacts',
    icon: UsersRound,
    description: 'Construa relacionamentos que vão além da primeira venda.',
    phase: 5,
  },
  {
    group: 'Comercial',
    label: 'Empresas',
    href: '/companies',
    icon: Building2,
    description: 'Organize seus relacionamentos com empresas.',
    phase: 5,
  },
  {
    group: 'Comercial',
    label: 'Leads',
    href: '/leads',
    icon: Magnet,
    description: 'O ponto de partida de novas oportunidades.',
    phase: 6,
  },
  {
    group: 'Comercial',
    label: 'Pipeline',
    href: '/pipeline',
    icon: Columns3,
    description: 'Acompanhe cada etapa da jornada comercial.',
    phase: 6,
  },
  {
    group: 'Atendimento',
    label: 'Conversas',
    href: '/conversations',
    icon: MessagesSquare,
    description: 'Conexões próximas, em um só lugar.',
    phase: 8,
  },
  {
    group: 'Atendimento',
    label: 'Tarefas',
    href: '/tasks',
    icon: CheckSquare,
    description: 'Dê atenção ao que precisa acontecer a seguir.',
    phase: 7,
  },
  {
    group: 'Vendas',
    label: 'Orçamentos',
    href: '/quotes',
    icon: FileText,
    description: 'Propostas claras para decisões melhores.',
    phase: 10,
  },
  {
    group: 'Vendas',
    label: 'Produtos',
    href: '/products',
    icon: Package,
    description: 'Um catálogo organizado para sua equipe.',
    phase: 9,
  },
  {
    group: 'Gestão',
    label: 'Automações',
    href: '/automations',
    icon: Workflow,
    description: 'Mais tempo para os relacionamentos importantes.',
    phase: 11,
  },
  {
    group: 'Gestão',
    label: 'Relatórios',
    href: '/reports',
    icon: ChartNoAxesCombined,
    description: 'Informação para orientar suas decisões.',
    phase: 12,
  },
  {
    group: 'Gestão',
    label: 'Equipe',
    href: '/team',
    icon: Users,
    description: 'Pessoas conectadas por um mesmo objetivo.',
    phase: 4,
  },
  {
    group: 'Sistema',
    label: 'Configurações',
    href: '/settings',
    icon: Settings2,
    description: 'Um espaço de trabalho alinhado à sua operação.',
    phase: 4,
  },
] as const;
export const groups = [...new Set(navigation.map((item) => item.group))];
export function currentPage(pathname: string) {
  return navigation.find((item) => pathname === item.href || pathname.startsWith(`${item.href}/`));
}
